In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [3]:
type(x)

numpy.ndarray

In [4]:
x.shape

(2, 3)

In [5]:
x.dtype

dtype('int32')

In [6]:
x[1]

array([4, 5, 6], dtype=int32)

In [7]:
x[1,2]

6

In [8]:
y = x[:, 1]

In [9]:
y.shape

(2,)

In [10]:
y.dtype

dtype('int32')

In [11]:
y

array([2, 5], dtype=int32)

In [12]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [13]:
y[0] = 90

In [14]:
y

array([90,  5], dtype=int32)

In [15]:
x

array([[ 1, 90,  3],
       [ 4,  5,  6]], dtype=int32)

In [16]:
#x has changed as well, a shallow copy upon assignment of slicing